theme = "solarized-dark"
icons = "awesome5"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "net"
device = "enp38s0"
format = "{ip} {speed_down; K*b} {speed_up; K*b}"
interval = 5

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization} {frequency}"

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "time"
format = "%a %d/%m %R"
